author: miniL
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
debug: true
# 邮箱API的地址
emailApiUrl: 'http://www.nmsl.tech/api/sendMail'

login:
      api: 'http://www.nmsl.tech/api/RLlogin'
#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第一个用户配置
  # 以下配置为工作日志
  - user:
        # 任务类型（收集：0、签到：1、查寝2）
        type: 0
        # 学校名称
        schoolName: '长春理工大学'
        # 账号
        username: 
        # 密码
        password: 
        # 定位位置信息
        address: '长春市'
        #email 接受通知消息的邮箱
        email: 
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        # 经纬度信息
        lon: 125.32279
        #经纬度信息
        lat: 43.836112
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 0
        # 表单信息
        forms:
            - form:
                  title: 身体是否有发热、咳嗽、发力、呼吸困难等症状
                  type: 2
                  value: 否，无以上症状
